### ISSUE TITLE
Req: dex SHA-1 signature repair, not just alder32 checksum

### ISSUE THREAD

**Issue by gps3dx** [anestisb/dexRepair#2]
Dear @anestisb 
as known, dexRepair can fix dex file alder32 checksum, but not its SHA-1 signature.
can you please add SHA-1 signature repair as well to dexRepair ?

IMHO, it would be advisable to separate it as a different switch then the already existing checksum repair, since SHA-1 repair should come before adler32 checksum and that SHA-1 calculation is considerable longer then alder32 checksum calculation. 

I hope you can add such feature to the already great dexRepair :-)

P.S - [as i'm a user in this repo(not dev)](https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/), I can't label this issues at all - only you can @anestisb.

**Comment by anestisb** [comment]
Done in commit https://github.com/anestisb/dexRepair/commit/fe264201ee0ceea780fe1c9814cef5d0cdf1115d

You can use the `-S,  --repair-sha` flag to enable this new feature, since it's disabled by default.

Let me know if that worked for you.

PS: Btw out of curiosity where exactly have you find it useful to repair the SHA-1 of DEX files? I've came across and developed various services and tools that worked with DEX files, and none of them appeared to make any meaningful use of the SHA-1 hash.

**Comment by gps3dx** [comment]
> where exactly have you find it useful to repair the SHA-1 of DEX files?

IMHO, theming an app ( e.i background color change etc ) is done faster by hex editing a dex, then the usual theming by decompilation to smali.

thanks again for the fast reply.
I'll try the new commit and will report soon.

lastly, a Q:
does the new switch "-S" execute SHA-1 repair of a dex, with or without adler32 checksum repair ?
i.e should I run dexrepair twice for both SHA-1 & checksum repair (in that repair order)?

**Comment by anestisb** [comment]
The CRC repair is always running regardless of the SHA repair flag. So yes if you enable the SHA1 repair the CRC will be repaired to.

**Comment by gps3dx** [comment]
>Done in commit fe26420
Let me know if that worked for you.

it works ! amazing !

I compared with an hex editor, the output of dexRepair VS other (VERY SLOW) method that I know that works on my phone - and dexRepair is blazing fast ! ( for ~6mb dex input, its ~4 secs with dexRepair vs ~3min with the other method on the same device&kernel )

moreover, on my arm64 phone with aarch64 kernel I can use either 'dexRepair_arm', 'dexRepair-armeabi and 'dexRepair-armeabi-v7a' without any problem or speed difference in comparison to 'dexRepair-arm64-v8a'

THANK YOU VERY MUCH !!!!
YOU'RE SIMPLY THE BEST ! 👍 👍 👍

**Comment by anestisb** [comment]
Glad it worked for you.
